{"time":"2024-11-30T15:26:50.6278025+01:00","level":"INFO","msg":"using version","core version":"0.18.6"}
{"time":"2024-11-30T15:26:50.6278025+01:00","level":"INFO","msg":"created symlink","path":"F:\\dl lab\\dl-lab-24w-team04-feature\\Jiang241023\\wandb\\run-20241130_152650-jbfdfeap\\logs\\debug-core.log"}
{"time":"2024-11-30T15:26:50.7536961+01:00","level":"INFO","msg":"created new stream","id":"jbfdfeap"}
{"time":"2024-11-30T15:26:50.7536961+01:00","level":"INFO","msg":"stream: started","id":"jbfdfeap"}
{"time":"2024-11-30T15:26:50.7536961+01:00","level":"INFO","msg":"sender: started","stream_id":"jbfdfeap"}
{"time":"2024-11-30T15:26:50.7536961+01:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"jbfdfeap"}}
{"time":"2024-11-30T15:26:50.7536961+01:00","level":"INFO","msg":"handler: started","stream_id":{"value":"jbfdfeap"}}
{"time":"2024-11-30T15:26:51.0145667+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-11-30T15:27:21.0178534+01:00","level":"ERROR","msg":"monitor: cpu: error sampling metrics: couldn't find pid: 1736"}
{"time":"2024-12-01T08:27:50.6277109+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-01T08:27:52.8638813+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-01T15:28:34.9979514+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": read tcp 192.168.0.102:62070->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-02T09:27:03.7587645+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-02T09:27:05.8401277+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-03T09:14:20.5682469+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-03T09:14:22.8605499+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-03T10:15:38.547597+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-03T15:00:39.7747817+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-03T15:19:19.8117949+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": read tcp 192.168.0.102:49812->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2024-12-03T16:45:39.7791567+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-03T19:45:39.7807352+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/uncategorized/jbfdfeap/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
