{"time":"2024-11-27T17:59:51.7923119+01:00","level":"INFO","msg":"using version","core version":"0.18.6"}
{"time":"2024-11-27T17:59:51.7923119+01:00","level":"INFO","msg":"created symlink","path":"F:\\dl lab\\dl-lab-24w-team04-feature\\Jiang241023\\wandb\\run-20241127_175951-yixtaeiz\\logs\\debug-core.log"}
{"time":"2024-11-27T17:59:51.9197976+01:00","level":"INFO","msg":"created new stream","id":"yixtaeiz"}
{"time":"2024-11-27T17:59:51.9197976+01:00","level":"INFO","msg":"stream: started","id":"yixtaeiz"}
{"time":"2024-11-27T17:59:51.9197976+01:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"yixtaeiz"}}
{"time":"2024-11-27T17:59:51.9197976+01:00","level":"INFO","msg":"handler: started","stream_id":{"value":"yixtaeiz"}}
{"time":"2024-11-27T17:59:51.9197976+01:00","level":"INFO","msg":"sender: started","stream_id":"yixtaeiz"}
{"time":"2024-11-27T17:59:52.2040165+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-11-27T18:09:52.2105928+01:00","level":"ERROR","msg":"monitor: cpu: error sampling metrics: couldn't find pid: 39492"}
{"time":"2024-11-27T19:27:22.8269488+01:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/yixtaeiz/file_stream"}
{"time":"2024-11-28T03:30:38.236857+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/yixtaeiz/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-28T05:15:38.243067+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/yixtaeiz/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-28T05:30:38.2493462+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/jiangyueyang2023de-university-of-stuttgart/diabetic-retinopathy-detection/yixtaeiz/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
